#!/usr/bin/env bash
# Print "Best School" 10 times for the 9th print Best School and then Hi.

count=1
while [ $count -le 10 ]
do
	if [ $count -eq 9 ] 
then
	echo "Best School"
	echo "Hi"
else
	echo "Best School"
fi
	((count++))
done
