#!/usr/bin/env bash
# A script that loops from 1 to 10, 4 bad luck, 8 good luck, Best school other

count=1
while [ $count -le 10 ]
do
if [ $count -eq 4 ]
then 
	echo "bad luck"
elif [ $count -eq 8 ]
then
	echo "good luck"
else 
	echo "Best School"
fi
	((count++))
done

